vote_athlete:
    resource: "@VoteBundle/Controller/AthleteController.php"
    type:     annotation

vote_epreuve:
    resource: "@VoteBundle/Controller/EpreuveController.php"
    type:     annotation

vote:
    resource: "@VoteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"