<?php

namespace VoteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountVotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountVotesRepository extends EntityRepository
{
}
